# Generated by Django 5.1 on 2024-09-01 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_audituserlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audituserlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
