# Generated by Django 5.1 on 2024-09-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_audituserlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audituserlog',
            name='name',
        ),
    ]
