# Generated by Django 5.1 on 2024-09-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_audituserlog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audituserlog',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
    ]
