# Generated by Django 5.1 on 2024-09-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_labels_card'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labels',
        ),
    ]
