# Generated by Django 5.1 on 2024-09-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile_unique_first_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='finish_Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='starts_Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
