# Generated by Django 5.1 on 2024-09-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_boardmember_board_alter_boardmember_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='base/card_images')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_files', to='base.card')),
            ],
        ),
    ]
