# Generated by Django 5.1 on 2024-09-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_cardfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardFiles',
            new_name='CardFile',
        ),
    ]
