# Generated by Django 5.1 on 2024-09-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_cardfiles_cardfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfile',
            name='file',
            field=models.FileField(upload_to='base/'),
        ),
    ]
