# Generated by Django 5.1 on 2024-09-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_cardfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfile',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
