# Generated by Django 5.1 on 2024-09-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_cardfile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardfile',
            name='images',
        ),
    ]
