# Generated by Django 5.1 on 2024-09-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_board_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
