# Generated by Django 5.1 on 2024-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_list_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='finish_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='starts_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
