# Generated by Django 5.1 on 2024-09-05 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_card_finish_date_alter_card_starts_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cardmember',
            constraint=models.UniqueConstraint(fields=('card', 'user'), name='unique_members'),
        ),
    ]
