# Generated by Django 5.1 on 2024-09-05 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_cardmember_unique_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cardmember',
            name='unique_members',
        ),
        migrations.AddConstraint(
            model_name='cardmember',
            constraint=models.UniqueConstraint(fields=('card', 'user'), name='unique_card_members'),
        ),
    ]
