# Generated by Django 5.1 on 2024-09-05 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_cardmember_unique_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boardmember',
            constraint=models.UniqueConstraint(fields=('board', 'user'), name='unique_board_members'),
        ),
    ]
