# Generated by Django 5.1 on 2024-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_boardmember_unique_board_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
