# Generated by Django 5.1 on 2024-09-11 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_boardmember_role_cardcomments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardComments',
            new_name='CardComment',
        ),
    ]
