# Generated by Django 5.1 on 2024-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_cardcomments_cardcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-21T18:47:00Z'),
            preserve_default=False,
        ),
    ]
