# Generated by Django 5.1 on 2024-09-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_cardcomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='date',
            field=models.DateField(auto_now_add=True, default='2020-04-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardcomment',
            name='time',
            field=models.TimeField(auto_now_add=True, default='8:1'),
            preserve_default=False,
        ),
    ]
